apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ui-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-ui-app
  template:
    metadata:
      labels:
        app: demo-ui-app
    spec:
      containers:
        - name: demo-ui-app
          image: "pongsathorn/demo-ui-dev:2024.02.00-0001-alpha"
          env:
            - name: SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: demo-ui-configmap
                  key: SERVER_URL
          ports:
            - containerPort: 80
